[package]
name = "rudis"
version = "0.1.0"
edition = "2024"

[profile.dev]
opt-level = 2

[dependencies]
nom = "8.0.0"
thiserror = "2.0.18"
tokio = { version = "1.52.3", features = ["full"] }
tokio-stream = { version = "0.1.18", features = ["net"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
